ci(workflow): add auto-merge-pr workflow
okp4/actions pull request #24
Opened 2022-09-20 14:35 UTC by hleonardtek

To enhance automation, this PR introduces automatic merge of PR's with all approvals.

2022-09-20 16:06 UTC, ccamel commented on src/.github/workflows/auto-merge-pr.yaml
> +    name: Merge
By convention, we don't name jobs, so I'd remove this line.

2022-09-20 16:07 UTC, ccamel commented on src/.github/workflows/auto-merge-pr.yaml
> +      - name: Integration check
```suggestion
      - name: Merge the PR (after approval)
```

2022-09-20 16:18 UTC, ad2ien reviewed
It's going to be nice 😃

2022-09-20 16:18 UTC, ad2ien commented on src/.github/workflows/auto-merge-pr.yaml
> +          delete_source_branch: false
let's delete the branch don't you think?

2022-09-21 07:59 UTC, ccamel approved these changes
👍

2022-09-21 08:33 UTC, ad2ien approved these changes
thanks!

2022-09-21 09:54 UTC, ad2ien reviewed
Actually, @amimart don't you think we should add it to auto-merge.yml instead?

2022-09-21 12:02 UTC, amimart requested changes
I'm not convinced by the approach, this is a tricky and very sensible subject that should be managed carefully,, and potentially with different approach depending on the project.

I think the first step before considering automatic merge is the categorization of the PR (e.g. dependency update, feature, fix, breaking change, etc...). Then, depending on the category we can set reviewers and assignees, and eventually automatically merge with different policies regarding the category.

2022-09-29 09:29 UTC, hleonardtek commented
Issue closed because we need to clarify the issue and categorize PR's.
For some use cases we don't want to merge the code as soon as we get all the approvals, there are consequences. For example, a merge in the platform-cloud repo may involve argo-cd to deploy stuff on k8s.

2022-09-29 09:29 UTC, closed without merging